# Generated by Django 5.1.5 on 2025-02-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go_Hire_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
